version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: apphoy:django
    container_name: apphoy_container
    command: python manage.py runserver 0.0.0.0:8000