# Generated by Django 3.2.14 on 2022-08-01 20:35

import django.contrib.postgres.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None), null=True, size=None, verbose_name='Phone numbers')),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254), null=True, size=None, verbose_name='E-mail addresses')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('nin', models.CharField(blank=True, max_length=50, null=True, verbose_name='National Insurance Number')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('t_shirt_size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=4, null=True, verbose_name='T-shirt size')),
                ('t_shirt_cut', models.CharField(blank=True, choices=[('W', 'Woman'), ('M', 'Man')], max_length=1, null=True, verbose_name='T-shirt cut')),
            ],
        ),
    ]
