# Generated by Django 3.2.16 on 2022-11-09 19:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None), null=True, size=None, verbose_name='Phone numbers')),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254), null=True, size=None, verbose_name='E-mail addresses')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('tin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Identification Number')),
                ('website', models.URLField(blank=True, max_length=100, null=True, verbose_name='Website')),
            ],
        ),
        migrations.CreateModel(
            name='Tent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=50, verbose_name='Name')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('room_number', models.IntegerField(blank=True, null=True, verbose_name='Number of rooms')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tents', to='accommodation.accommodationcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=50, verbose_name='Name')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('square_footage', models.IntegerField(blank=True, null=True, verbose_name='Square footage')),
                ('number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Room number')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Floor')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accommodation.accommodationcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=50, verbose_name='Name')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('square_footage', models.IntegerField(blank=True, null=True, verbose_name='Square footage')),
                ('floor_number', models.IntegerField(blank=True, null=True, verbose_name='Number of floors')),
                ('room_number', models.IntegerField(blank=True, null=True, verbose_name='Number of rooms')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='accommodation.accommodationcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=50, verbose_name='Name')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('square_footage', models.IntegerField(blank=True, null=True, verbose_name='Square footage')),
                ('number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Flat number')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Floor')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='accommodation.accommodationcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=50, verbose_name='Name')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('room_number', models.IntegerField(blank=True, null=True, verbose_name='Number of rooms')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model')),
                ('built_year', models.DateField(blank=True, null=True, verbose_name='Year built')),
                ('main_propulsion', models.CharField(blank=True, choices=[('engine', 'Engine'), ('sails', 'Sails'), ('paddles', 'Paddles')], max_length=50, null=True, verbose_name='Main propulsion')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='Length')),
                ('height_inside', models.IntegerField(blank=True, null=True, verbose_name='Height inside')),
                ('sail_size', models.IntegerField(blank=True, null=True, verbose_name='Sail size')),
                ('engine_power', models.IntegerField(blank=True, null=True, verbose_name='Engine power')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boats', to='accommodation.accommodationcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccommodationCompanyStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None), null=True, size=None, verbose_name='Phone numbers')),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254), null=True, size=None, verbose_name='E-mail addresses')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accommodation.accommodationcompany')),
            ],
        ),
    ]
